spring.application.name=clinique-api
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/clinique_db?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

app.jwt.secret=Y2xpbmlxdWUtbWVkaWNhbGUtc2VjcmV0LWtleS1zcHJpbmctYm9vdC1qd3QtaHMyNTYtMjAyNg==
app.jwt.expiration-ms=86400000

app.admin.email=admin@clinique.com
app.admin.password=Admin@123

app.notification.rappel-heures-avant=24

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
